### ISSUE TITLE
Key not supported consider redundant

### ISSUE THREAD

**Issue by sonder-joker** [WebAssembly/wasi-crypto#45]
Durning design test, I notice one thing that [error code](https://github.com/WebAssembly/wasi-crypto/blob/main/docs/wasi-crypto.md#errors) `key_not_supported` can never return. 
For the chosen algorithm doesn't support keys,  when you try to generate by `key_generate/key_import`,  it always return error code `invaild_operation`, which mean you never get a key that underlying algorithm doesn't support key. 
And when you input other kind key, it always return a  `invaild_key` before get `key_not_supported`

**Comment by jedisct1** [comment]
`key_not_supported` is returned when a key was provided, but the function doesn't support keys.

WIth the current algorithms, it can be returned when a key has been supplied with SHA-2 (the hash function, not in a HMAC construction). Other hash functions can support an optional key.

**Comment by jedisct1** [comment]
`key_generate()`/`key_import()` should return `key_not_supported` in that case. Or do you think the generic `invalid_operation` error would be good enough in that context?

The distinction can be useful to applications, but if this makes the implementation more complicated, we can indeed merge both error codes.

**Comment by sonder-joker** [comment]
Oh I misunderstood the code. Thanks, I think `key_not_supported` is well enough .
