### ISSUE TITLE
Support more feature.

### ISSUE THREAD

**Issue by sonder-joker** [WebAssembly/wasi-crypto#52]
I have tried to port wasi-crypto to [RustCrypto/traits](https://github.com/RustCrypto/traits).
Compare with RustCrypto target wasm32-wasi, it have Ssgnificant speed increase.
However, I meet some feature we don't have. I will record them here.

**Comment by sonder-joker** [comment]
Support `symmetric_state_reset`.
Instead of recreate a new `state`, reset is more efficient.

**Comment by sonder-joker** [comment]
Support `symmetric_state_copy`
A deep copy of `state` return a new handle. I believe it will be easy for people want to copy.
Beside, RustCrypto/Traits require a deep copy.

**Comment by sonder-joker** [comment]
After support [RustCrypto/traits](https://github.com/RustCrypto/traits), we can also use RustCrypto test for #52. [My preliminary implementation](https://github.com/sonder-joker/wasi-crypto-rust-crypto) here.

**Comment by jedisct1** [comment]
I'm not too fan of `symmetric_state_reset`.

Some ciphers and keyed hash functions using a rolling state have a really useful property: if a state is leaked, the initial state or the key cannot be recovered.

Supporting a `reset` operation defeats this, and requiers keeping a copy of the secret key or the initial state forever. Even if `reset` is never called.

**Comment by sonder-joker** [comment]
> I'm not too fan of `symmetric_state_reset`.
> 
> 
> 
> Some ciphers and keyed hash functions using a rolling state have a really useful property: if a state is leaked, the initial state or the key cannot be recovered.
> 
> 
> 
> Supporting a `reset` operation defeats this, and requiers keeping a copy of the secret key or the initial state forever. Even if `reset` is never called.
> 
> 
> 
> 

Thank you for your advice. Supporting reset is inappropriate.
