### ISSUE TITLE
curve25519-dalek unmaintained

### ISSUE THREAD

**Issue by npmccallum** [WebAssembly/wasi-crypto#63]
I filed a PR against `curve25519-dalek` to update dependencies:

https://github.com/dalek-cryptography/curve25519-dalek/pull/403

However, it appears that the crate is unmaintained and forces old dependencies all downstreams. There are numerous PRs requesting dependency updates that have all been ignored: https://github.com/dalek-cryptography/curve25519-dalek/pulls

I recommend we drop this curve OR make it optional until such time as a practical implementation can be made.

@rjzak @tarcieri

**Comment by jedisct1** [comment]
There's `curve25519-dalek-ng`, a fork that resulted from an internal drama, but the least release is actually older than `curve25519-dalek`.

An alternative would be to use BoringSSL (that supports X25519 and Ed25519).

**Comment by tarcieri** [comment]
We've had some previous requests to fork the dalek crates under @RustCrypto.

If that sounds interesting to you, it'd be helpful if you could leave a note about your use cases on this issue: https://github.com/RustCrypto/elliptic-curves/issues/497

**Comment by jedisct1** [comment]
`ed25519-dalek` was replaced with `ed25519-compact`.
